services:
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    volumes:
      - ./docs:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    # comando para inicializar o serviço para o endereço da UI
    command: server /data --console-address ":9001"
    restart: unless-stopped
