version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio
    ports:
      - "${HOST_MINIO_PORT}:9000" #API
      - "${HOST_MINIO_UI_PORT}:9001" #Console Web
    volumes:
      - ./docs:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: unless-stopped