spring:
  application:
  name: billing
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest # Para obter mensagens das mais antigas Ã s mais novas. Isso evita perda de dados.
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: i18n/messages
    encoding: UTF-8

server:
  port: ${SERVER_PORT}

market-sphere:
  config:
    kafka:
      topics:
        paid-orders: ${KAFKA_TOPIC_PAID_ORDERS}
        billed-orders: ${KAFKA_TOPIC_BILLED_ORDERS}
        shipped-orders: ${KAFKA_TOPIC_SHIPPED_ORDERS}

minio:
  url: ${MINIO_ENDPOINT_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BILLING_BUCKET}
#  url: ${MINIO_HOST}:${MINIO_PORT}
