spring:
  application:
  name: billing
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest # Para obter mensagens das mais antigas Ã s mais novas. Isso evita perda de dados.
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: ${SERVER_PORT}

market-sphere:
  config:
    kafka:
      topics:
        paid-orders: ${KAFKA_TOPIC_PAID_ORDERS}
        billed-orders: ${KAFKA_TOPIC_BILLED_ORDERS}
        shipped-orders: ${KAFKA_TOPIC_SHIPPED_ORDERS}

minio:
  url: http://${MINIO_HOST}:${MINIO_PORT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BILLING_BUCKET}
